apiVersion: nais.io/v1alpha1
kind: Application

metadata:
    name: meldekort-backend
    namespace: aap
    labels:
        team: aap
        sub: meldekort-backend

spec:
    ingresses:
        - https://aap-meldekort-backend.intern.dev.nav.no
    image: {{image}}
    strategy:
        type: Recreate
    port: 8080
    replicas:
        max: 1
        min: 1
    resources:
        limits:
            memory: 512Mi
        requests:
            cpu: 500m
            memory: 512Mi
    observability:
        autoInstrumentation:
            enabled: true
            runtime: "java"
        logging:
            destinations:
                - id: elastic
                - id: loki
    prometheus:
        enabled: true
        path: /actuator/metrics
    tokenx:
        enabled: true
    azure:
        application:
            enabled: true
            ## Dette blir feil, er ikke nav-ansatte som logger inn ...
            allowAllUsers: true
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
    liveness:
        path: /actuator/live
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    readiness:
        path: /actuator/ready
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    secureLogs:
        enabled: true
    accessPolicy:
        inbound:
            rules:
                - application: meldekort
                - application: tokenx-token-generator
                  namespace: aura

                  # TODO: fjern, skal bare bruke tokenx for innkommende kall
                - application: azure-token-generator
                  namespace: aura
    gcp:
        sqlInstances:
            - type: POSTGRES_16
              tier: db-f1-micro
              databases:
                  - name: meldekort-backend
                    envVarPrefix: DB