apiVersion: nais.io/v1alpha1
kind: Application

metadata:
    name: meldekort-backend
    namespace: aap
    labels:
        team: aap
        sub: meldekort-backend
    annotations:
        texas.nais.io/enabled: "true"

spec:
    image: {{image}}
    port: 8080
    resources:
        limits:
            memory: 512Mi
        requests:
            cpu: 500m
            memory: 512Mi
    observability:
        autoInstrumentation:
            enabled: true
            runtime: "java"
        logging:
            destinations:
                - id: elastic
                - id: loki
    prometheus:
        enabled: true
        path: /actuator/metrics
    tokenx:
        enabled: true
    azure:
        application:
            enabled: true
    liveness:
        path: /actuator/live
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    readiness:
        path: /actuator/ready
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    secureLogs:
        enabled: true
    accessPolicy:
        inbound:
            rules:
                - application: meldekort
                - application: behandlingsflyt
                - application: paw-patrol
        outbound:
            rules:
                - application: api-intern
                - application: pdfgen-meldekort
            external:
                - host: dokarkiv.prod-fss-pub.nais.io
    gcp:
        sqlInstances:
            - type: POSTGRES_16
              tier: db-custom-1-3840
              databases:
                  - name: meldekort-backend
                    envVarPrefix: DB
    env:
        - name: MELDEKORTSERVICE_URL
          value: https://meldekortservice.prod-fss-pub.nais.io/meldekortservice/api
        - name: MELDEKORTSERVICE_SCOPE
          value: prod-fss:meldekort:meldekortservice
        - name: MELDEKORTKONTROLL_URL
          value: https://meldekortkontroll-api.prod-fss-pub.nais.io
        - name: MELDEKORTKONTROLL_SCOPE
          value: prod-fss:meldekort:meldekortkontroll-api
        - name: DOKARKIV_URL
          value: https://dokarkiv.prod-fss-pub.nais.io
        - name: DOKARKIV_SCOPE
          value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
        - name: AAP_API_INTERN_URL
          value: http://api-intern.aap/
        - name: AAP_API_INTERN_SCOPE
          value: api://prod-gcp.aap.api-intern/.default
        - name: PDFGEN_URL
          value: http://pdfgen-meldekort.aap
#        - name: BEHANDLINGSFLYT_AZP
#          value: ????? # TODO: fyll inn når behandlingsflyt er deployet til prod
