[versions]
komponenter = "2.0.182"
tilgang = "1.0.242"
behandlingsflyt = "0.0.669"

[libraries]
# Kelvin
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
gateway = { module = "no.nav.aap.kelvin:gateway", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
ktorOpenApiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }

# Tilgang
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
tilgangApiKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }

# Behandlingsflyt
behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }
# Varsel
varselKotlinBuilder = { module = "no.nav.tms.varsel:kotlin-builder", version = "2.2.0" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.6.1" }
