name: Bygg og deploy

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'

jobs:
    gradle:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        permissions:
            contents: write
            actions: read
            checks: write
            id-token: write
        uses: navikt/aap-workflows/.github/workflows/gradle-build.yml@main
        secrets: inherit

    dev:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'dev-gcp'
        permissions:
            contents: read
            id-token: write
        needs: gradle
        uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            cluster: dev-gcp
            manifest: .nais/dev-gcp.yml

    prod:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'prod-gcp'
        permissions:
            contents: read
            id-token: write
        needs: dev
        uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            cluster: prod-gcp
            manifest: .nais/prod-gcp.yml
